version: '1.0'
entity_code: '31A'
region: 'benelux'
enabled: true

connection:
  connection_ref: 'sftp_donnington'
  source_path: 'ITA/31A/ingress/prod/'

is_zip: true

document:
  document_type: 'items'
  file_pattern: 'products*'
  format: 'txt'
  csv_options:
    quote: "\""
    encoding: 'UTF-8'
    header: false
    delimiter: '\t'
    inferSchema: false
  header_schema:
    - productcode
    - description
  
contract:
  contract_path: 'contracts/seu/31a/items/contract.yaml'
  
transformations:
  custom_module: 
  custom_function: 'transform_item'  # Optional, if empty uses generic transformation
  
paths:
  checkpoint_bronze: '/Volumes/teamblue_finance/default/sagacity-data-teamblue-finance-dev/_checkpoints/bronze/billing/seu/31a/items'
  checkpoint_silver: '/Volumes/teamblue_finance/default/sagacity-data-teamblue-finance-dev/_checkpoints/silver/billing/invoices'