version: '1.0'
entity_code: '11U'
region: 'benelux'
enabled: true

connection:
  connection_ref: 'api_chargebee'  # Links to connections/API/api_entersoft.yaml
  
document:
  document_type: 'payments_refunds'
  file_pattern: '*.json'
  format: 'json'
  json_options:
    multiline: true
    inferSchema: true
  json_column_extract: 'list'
  
contract:
  contract_path: 'contracts/benelux/11u/payments_refunds/contract.yaml'
  
transformations:
  custom_module: 'resources.domains.finance.billing.core.transformations.custom.benelux.11U.payments_refunds'  # Optional
  custom_function: 'apply_transformation'  # Optional, if empty uses generic transformation
  
paths:
  # Auto-constructed from connection + entity + region + document_type
  checkpoint_bronze: '/Volumes/teamblue_finance/default/sagacity-data-teamblue-finance-dev/_checkpoints/bronze/billing/benelux/11u/payments_refunds'
  checkpoint_silver: '/Volumes/teamblue_finance/default/sagacity-data-teamblue-finance-dev/_checkpoints/silver/billing/payments' #!