version: '1.0'
entity_code: '31A-SF'
region: 'benelux'
enabled: true

connection:
  connection_ref: 'sftp_donnington'
  source_path: 'ITA/31A-SF/ingress/prod/'

is_zip: true

document:
  document_type: 'items'
  file_pattern: '*items*'
  format: 'txt'
  csv_options:
    quote: "\""
    encoding: 'UTF-8'
    header: true
    delimiter: '\t'
    inferSchema: true

expectations:
  "item_id_not_null": "item_id IS NOT NULL"
  "item_group_not_null": "item_group IS NOT NULL"
  "description_not_null": "description IS NOT NULL"
  "ext_code_not_null": "ext_code IS NOT NULL"
  
contract:
  contract_path: 'contracts/seu/31A-SF/items/contract.yaml'
  
transformations:
  custom_module: 
  custom_function: 'transform_customer'  # Optional, if empty uses generic transformation
  
paths:
  checkpoint_bronze: '/Volumes/teamblue_finance/default/sagacity-data-teamblue-finance-dev/_checkpoints/bronze/billing/seu/31a-sf/items'
  checkpoint_silver: '/Volumes/teamblue_finance/default/sagacity-data-teamblue-finance-dev/_checkpoints/silver/billing/items'